config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resources :dfiles

  resources :edmrecords

end

app/models/edmrecord.rb
class Edmrecord < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dfiles_controller.rb
class DfilesController < ApplicationController
  def new
  
  end

  def create

    if filename=uploadFile(params[:file]['file'])
      render :text=>filename
    end
    render plain: params[:dfile].inspect

  end

  def uploadFile(file)
    if !file.filename.empty?
      @filename=getFileName(file.filename)
      File.open("#{RAILS_ROOT}/public/images/#{@filename}", "wb") do |f|
        f.write(file.read)
      end
      return @filename
    end
  end

  def getFileName(filename)
    if !filename.nil?
      return filename
    end
  end

end

app/controllers/edmrecords_controller.rb
class EdmrecordsController < ApplicationController

def new
  mailid = params[:mailid]
  edmid  = params[:edmid]
  @edmrecord = Edmrecord.new
  @edmrecord.mailid= mailid
  @edmrecord.edmid = edmid
  @edmrecord.save
  redirect_to @edmrecord
end

def index
  @edmrecords = Edmrecord.all
end

def show
  @edmrecord = Edmrecord.find(params[:id])
end 


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dfiles_helper.rb
module DfilesHelper
end

app/helpers/edmrecords_helper.rb
module EdmrecordsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dfiles/new.html.erb
<h> hi i am here </h>

<%= form_for :dfile ,url: dfiles_path,multipart:true do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <input type="file" name="file[file]">
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/edmrecords/index.html.erb
<h1>Listing articles</h1>
 
 <p> a litter modification from dev client</p>
 
 <p> second litter modification from dev client</p>
 
 <p> new modification in the dev branch</p>
 
 <p> new modification in the local dev branch </p>
 
<table>
  <tr>
    <th>edm id</th>
    <th>mail id</th>
    <th>time </th>
  </tr>
 
  <% @edmrecords.each do |edmrecord| %>
    <tr>
      <td><%= edmrecord.edmid %></td>
      <td><%= edmrecord.mailid %></td>
      <td><%= edmrecord.created_at.to_s(:long) %> </td>
    </tr>
  <% end %>
</table>

app/views/edmrecords/show.html.erb
<p>
  <strong>Edmid:</strong>
  <%= @edmrecord.edmid %>
</p>
 
<p>
  <strong>MailId:</strong>
  <%= @edmrecord.mailid %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Building</h1>
<h1>Comming soon.... </h1>
<p>建设中.....</p>